### ISSUE TITLE
URL Error when using Munki 4 and above

### ISSUE THREAD

**Issue by IndulgentHuman** [sphen13/B2-Middleware#4]
Using the provided instructions with Munki 4 and above produces the following error. 

A workaround for this error is to change the python symlink in the munki folder located at /usr/local/munki/python to point to the python installed on macOS located at /usr/bin/python.

`Starting...
    No CA cert info provided, so nothing to add to System keychain.
    No client cert info provided, so no client keychain will be created.
Checking for available updates...
    Manifest base URL is: https://b2/SCREPO/manifests/
    Getting manifest testing...
    Options: {'url': 'https://b2/SCREPO/manifests/testing', 'file': '/Library/Managed Installs/manifests/testing.download', 'follow_redirects': 'none', 'ignore_system_proxy': False, 'can_resume': False, 'additional_headers': {'User-Agent': 'managedsoftwareupdate/5.0.1.4059 Darwin/19.6.0'}, 'download_only_if_changed': False, 'cache_data': None, 'logging_function': <function display_debug2 at 0x7fbb5e75a560>, 'pkginfo': None}
    Processing options through middleware
B2-Middleware: URLError <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
B2-Middleware: Not Authorized.
    Options: {'url': 'https://b2/SCREPO/manifests/testing', 'file': '/Library/Managed Installs/manifests/testing.download', 'follow_redirects': 'none', 'ignore_system_proxy': False, 'can_resume': False, 'additional_headers': {'User-Agent': 'managedsoftwareupdate/5.0.1.4059 Darwin/19.6.0'}, 'download_only_if_changed': False, 'cache_data': None, 'logging_function': <function display_debug2 at 0x7fbb5e75a560>, 'pkginfo': None}
    Download error -1001: The request timed out.
    Headers: None
ERROR: Could not retrieve managed install primary manifest.
    Nothing found to precache.
Finishing...
    Getting info on currently installed applications...
Done.
`

**Comment by perren** [comment]
Can confirm. Was working during my setup yesterday, then all of the sudden, splat: the godaddy-root.pem wasn't doing the trick.

B2 moved away from that CA some time ago and I'm guessing finally flushed that cert out of their hosts across the board this week.

I smashed together a new chain for Let's Encrypt X3, replaced the godaddy root and it works again.

**Comment by sphen13** [comment]
Sorry for the delay here. I think PR #5 should fix.  Could you try it out?

https://github.com/sphen13/B2-Middleware/tree/v1.3.1

you will need to replace the middleware file as well as drop the new `b2-root.pem` into `/usr/local/munki/`

I should revisit this so the pem file is not needed. This will become a problem in March 2021 again- but at least then you just need to distribute a new pem file.

**Comment by perren** [comment]
Close! This one requires a full chain. Add the DST Root CA X3 cert and it will work.

**Comment by sphen13** [comment]
thanks @perren yeah just fully tested with full chain. pushed changes. now i will see if i can investigate going back to not requiring the CA cert like we used to. the bundle python3 in munki is lacking some of the functionality.

**Comment by sphen13** [comment]
actually now im thinking about just including standard the standard cafile from certifi - thoughts on this @perren ? i would hate for this to break in the future.

https://github.com/certifi/python-certifi/blob/master/certifi/cacert.pem

**Comment by sphen13** [comment]
i think this is the smartest path for now. i am watching the main cacert.pem and will update middleware for now accordingly. this should not break if backblaze switches to another cert in the future
